#!/bin/bash
# The logic to stop your application should be put in this script.
kill `ps -ef | grep glassfish | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1
#$OPENSHIFT_REPO_DIR/diy/glassfish3/glassfish/bin/adadmin stop-domain
exit 0
